"""
ContextGuard — Evaluation Metrics

Implements all four metrics from the proposal (§5 Evaluation Design):

  HR  — Hallucination Rate
        Percentage of the answer that is NOT supported by context.
        Derived from the Grounding Validator's CIS score: HR = 1 - CIS.

  CIS — Context Integrity Score
        How accurately the answer is grounded in context.
        Primary source: LLM judge in GroundingValidatorAgent.
        Blended with attribution_score for robustness.

  CUE — Context Utilization Efficiency
        CUE = Relevant Context Used / Total Relevant Context   (proposal §3)
        A context doc is "used" if its TF-IDF similarity to the answer
        exceeds the COVERAGE_THRESHOLD.

  RS  — Robustness Score
        Average resistance to adversarial context injections.
        RS = 1 - avg(similarity_to_adversarial_doc_across_trials)

Formal risk model (proposal §3):
  P(H) = 1 - ∏ P(context supports output)   → approximated by HR
  System constraints:  P(H) < τ (τ=0.30)   and   CUE > δ (δ=0.50)
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Proposal §3 system constraints
HALLUCINATION_THRESHOLD  = 0.30   # τ  — HR must stay BELOW this
CUE_THRESHOLD            = 0.50   # δ  — CUE must stay ABOVE this
COVERAGE_THRESHOLD       = 0.05   # minimum similarity to count a doc as "used"


def _compute_cue(answer: str, context_docs: list[str]) -> float:
    """
    CUE = (# context docs whose similarity to answer > COVERAGE_THRESHOLD)
          / (total # context docs)

    Addresses: Selective Attention Failure — checks every context segment.
    """
    if not context_docs or not answer.strip():
        return 0.0

    used = 0
    for doc in context_docs:
        try:
            vec = TfidfVectorizer().fit_transform([answer, doc])
            sim = float(cosine_similarity(vec[0], vec[1])[0][0])
        except ValueError:
            sim = 0.0
        if sim > COVERAGE_THRESHOLD:
            used += 1

    return round(used / len(context_docs), 4)


def _blend_cis(llm_cis: float, attribution_score: float) -> float:
    """
    Blend LLM-judge CIS (70%) and attribution score (30%) for robustness.
    Pure LLM CIS can be overconfident; attribution grounds it in token-level evidence.
    """
    return round(0.70 * llm_cis + 0.30 * attribution_score, 4)


def evaluate_response(
    answer:     str,
    context:    list[str],
    validation: dict,
    robustness: dict,
) -> dict:
    """
    Aggregate all four ContextGuard metrics into a single evaluation dict.

    Parameters
    ----------
    answer      : The answer generated by ReasoningAgent
    context     : List of retrieved context documents
    validation  : Output of GroundingValidatorAgent.validate()
    robustness  : Output of AdversarialTesterAgent.test_robustness()

    Returns
    -------
    dict with: hallucination_rate, cis_score, cue_score, robustness_score,
               overall_score, constraint_violations, formal_risk
    """

    # ── HR (Hallucination Rate) ───────────────────────────────────────────────
    hallucination_rate = validation.get("hallucination_risk", 0.5)

    # ── CIS (Context Integrity Score) ────────────────────────────────────────
    llm_cis = validation.get("cis_score", 0.5)
    attr    = validation.get("attribution", {})
    attr_score = attr.get("attribution_score", llm_cis)   # fallback to LLM CIS
    cis_score  = _blend_cis(llm_cis, attr_score)

    # ── CUE (Context Utilization Efficiency) ─────────────────────────────────
    cue_score = _compute_cue(answer, context)

    # ── RS (Robustness Score) ─────────────────────────────────────────────────
    robustness_score = robustness.get("robustness_score", 0.5)

    # ── Overall Score (weighted average) ─────────────────────────────────────
    # Weights reflect proposal priorities: CIS and HR are most critical
    overall_score = round(
        (1 - hallucination_rate) * 0.30
        + cis_score              * 0.30
        + cue_score              * 0.20
        + robustness_score       * 0.20,
        4,
    )

    # ── Formal Risk Model (proposal §3) ──────────────────────────────────────
    # P(H) = 1 - ∏ P(context supports output)
    # Approximated per-document as (1 - CIS) uniformly
    import math
    per_doc_support = max(0.0001, cis_score)   # avoid log(0)
    p_hallucination = 1.0 - math.exp(len(context) * math.log(per_doc_support))
    p_hallucination = max(0.0, min(1.0, p_hallucination))

    # ── Constraint violations ─────────────────────────────────────────────────
    violations = []
    if hallucination_rate >= HALLUCINATION_THRESHOLD:
        violations.append(
            f"P(H) = {hallucination_rate:.2%} ≥ τ ({HALLUCINATION_THRESHOLD:.0%}) — "
            "CONSTRAINT VIOLATED"
        )
    if cue_score < CUE_THRESHOLD:
        violations.append(
            f"CUE = {cue_score:.2%} < δ ({CUE_THRESHOLD:.0%}) — "
            "CONSTRAINT VIOLATED"
        )

    return {
        "hallucination_rate": hallucination_rate,
        "cis_score":          cis_score,
        "cue_score":          cue_score,
        "robustness_score":   robustness_score,
        "overall_score":      overall_score,
        "formal_p_hallucination": round(p_hallucination, 4),
        "constraint_violations":  violations,
        "verdict":            validation.get("verdict", "UNKNOWN"),
        "unsupported_claims": validation.get("unsupported_claims", []),
    }


def format_report(metrics: dict, query: str = "") -> str:
    """Pretty-print a metrics summary for console output."""
    lines = [
        "╔══════════════════════════════════════════════════════╗",
        "║          ContextGuard Evaluation Report              ║",
        "╚══════════════════════════════════════════════════════╝",
    ]
    if query:
        lines.append(f"  Query : {query[:70]}")
    lines += [
        f"  HR  (Hallucination Rate)        : {metrics['hallucination_rate']:.2%}",
        f"  CIS (Context Integrity Score)   : {metrics['cis_score']:.2%}",
        f"  CUE (Context Util. Efficiency)  : {metrics['cue_score']:.2%}",
        f"  RS  (Robustness Score)          : {metrics['robustness_score']:.2%}",
        f"  Overall Score                   : {metrics['overall_score']:.2%}",
        f"  Verdict                         : {metrics.get('verdict', '?')}",
        f"  Formal P(H)                     : {metrics.get('formal_p_hallucination', '?'):.4f}",
    ]
    if metrics.get("constraint_violations"):
        lines.append("  ⚠ Constraint Violations:")
        for v in metrics["constraint_violations"]:
            lines.append(f"      • {v}")
    if metrics.get("unsupported_claims"):
        lines.append("  ⚠ Unsupported Claims:")
        for c in metrics["unsupported_claims"]:
            lines.append(f"      • {c}")
    lines.append("─" * 56)
    return "\n".join(lines)
